---
abstract: 'User-Defined Character Properties for Joyo Kanji and Jinmeiyo Kanji'
author:
  - 'pawa <pawa@pawafuru.com>'
build_requires:
  Test::More: '0.99'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-JA-KanjiTable
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Lingua::JA::KanjiTable:
    file: lib/Lingua/JA/KanjiTable.pm
    version: '0.12'
requires:
  Exporter: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/pawa-/Lingua-JA-KanjiTable/issues
  homepage: https://github.com/pawa-/Lingua-JA-KanjiTable
  repository: git://github.com/pawa-/Lingua-JA-KanjiTable
version: '0.12'
