---
abstract: 'Kanji properties'
author:
  - 'pawa <pawa@pawafuru.com>'
build_requires:
  Test::More: 0.99
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-JA-KanjiTable
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Lingua::JA::KanjiTable:
    file: lib/Lingua/JA/KanjiTable.pm
    version: 0.01
requires:
  Exporter: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/pawa-/Lingua-JA-KanjiTable/issues
  homepage: https://github.com/pawa-/Lingua-JA-KanjiTable
  repository: git://github.com/pawa-/Lingua-JA-KanjiTable
version: 0.01
